### ISSUE TITLE
Issue with importing sympy 

### ISSUE THREAD

**Issue by crish99ubc** [Niuskir/Electron-Orbitals-Blender-3D#2]
I have issues with importing the functions. I made sure the modules are in the right file location for importing but although it can find sympy module it can import functions like symbols, I, simplify under it. I thought this would be some shadowing issue and delete other files and start anew. But I don't get a solution to the issue.

https://github.com/Niuskir/Electron-Orbitals-Blender-3D/blob/f0bc90fda4eb4730ab840744795cddc709348228/hydrogen_electron_orbitals.py#L15

**Comment by Niuskir** [comment]
I have updated the instructions with an easier method to add sympy and mpmath to Blender. Please try this and let me know.

**Comment by crish99ubc** [comment]
Wow, thanks a lot. This code is very helpful and the orbitals are absolutely beautiful. I'm working on creating models and helping first year students on developing visualizing skills in quantum chemistry. Thanks again.
